
# pick image with git and bash
ARG BASE=node:16

# --------------------

FROM ${BASE} AS dependencies
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# ---------------------

FROM ${BASE} AS development
WORKDIR /app

ENV NODE_ENV development

# copy source and node_modules separately
# source from host
COPY . .
# node_modules is .dockerignored on host
# node_modules from dependencies stage
COPY --from=dependencies /app/node_modules ./node_modules

EXPOSE 3001
ENV PORT 3001

RUN npx prisma generate

CMD [ "yarn", "migrate-dev" ]

