
# pick image with git and bash
# ARG BASE=mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
ARG BASE=node:16-bullseye

# --------------------
# no ENV vars required buildtime

FROM ${BASE} AS dependencies
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# ---------------------

FROM ${BASE} AS development
WORKDIR /app
ENV NODE_ENV development

# volumes folders must be created and chowned before docker-compose creates them as root
# create them during docker build, single chown -R node:node /app is fine
# COPY creates .next and node_modules, no need for mkdir

# copy source and node_modules separately
# source from host
COPY . .

# node_modules is .dockerignored on host
# node_modules from dependencies stage
COPY --from=dependencies /app/node_modules ./node_modules
RUN npx prisma generate

RUN chown -R node:node /app
USER node

RUN ls -la

EXPOSE 3001
ENV PORT 3001

CMD [ "yarn", "start-dev" ]
