
# use alpine for tests like prod
ARG BASE=node:16-alpine


#---------------------

FROM ${BASE} AS dependencies

# openssl for prisma client
RUN apk update && apk add --no-cache openssl libc6-compat

WORKDIR /app
ENV NODE_ENV development

COPY package.json yarn.lock ./
COPY prisma ./prisma

RUN yarn install
RUN npx prisma generate
RUN rm -rf prisma

#----------------------

# two stages so it doesnt install packages every time
FROM ${BASE} AS test
WORKDIR /app
ENV NODE_ENV test

# node_modules is .dockerignored on host
# source from host
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

# volumes folders must be created and chowned before docker-compose creates them as root
# create them during docker build
RUN mkdir -p .next
RUN chown node:node . node_modules .next dist
RUN chown -R node:node node_modules/.prisma

USER node

# debug
# RUN ls -la node_modules/.prisma/client

# on container
EXPOSE 3005
# env for app
ENV PORT 3001

CMD [ "yarn", "migrate-prod" ]
