
# use alpine for tests like prod
ARG BASE=node:16-alpine

# simplified prod build
# migrate, seed, build
#---------------------

FROM ${BASE} AS dependencies

# openssl for prisma client, bash for wait-for-it.sh
RUN apk update && apk add --no-cache openssl libc6-compat

WORKDIR /app
ENV NODE_ENV development

COPY package.json yarn.lock ./
COPY prisma ./prisma

# dev dependencies for testing
RUN yarn install
RUN npx prisma generate
RUN rm -rf prisma

#----------------------

# two stages so it doesnt install packages every time
FROM ${BASE} AS test
WORKDIR /app
ENV NODE_ENV test

# node_modules is .dockerignored on host
# source from host
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

# volumes folders must be created and chowned before docker-compose creates them as root
# create them during docker build
RUN mkdir -p .next dist
RUN chown node:node . node_modules .next dist
RUN chown -R node:node node_modules/.prisma

USER node

# on container
EXPOSE 3001
# env for app
ENV PORT 3001

# migrate prod, build app, start prod
# just migrate and shut down - for integration tests
# && start for e2e
CMD [ "yarn", "prisma:migrate:prod" ]
