
# pick image with git and bash
# ARG BASE=mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
ARG BASE=node:16-bullseye

# --------------------

FROM ${BASE} AS dependencies
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# ---------------------

FROM ${BASE} AS development
WORKDIR /app
ENV NODE_ENV development

ARG ARG_UID
ARG ARG_GID

RUN printenv && whoami
RUN mkdir /app/node_modules /app/.next
RUN chown ${ARG_UID}:${ARG_GID} /app /app/node_modules /app/.next

# copy source and node_modules separately
# source from host
COPY . .
# node_modules is .dockerignored on host
# node_modules from dependencies stage
# --chown=node:node
COPY --from=dependencies --chown=${ARG_UID}:${ARG_GID} /app/node_modules ./node_modules
RUN npx prisma generate

RUN chown -R ${ARG_UID}:${ARG_GID} /app
USER node

RUN ls -la

EXPOSE 3001
ENV PORT 3001

CMD [ "yarn", "start-dev" ]

